---
- name: Adjust kernel parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: "fs.inotify.max_queued_events"
      value: 16384
    - name: "fs.inotify.max_user_instances"
      value: 8192
    - name: "fs.inotify.max_user_watches"
      value: 524288

- name: Set fastestmirror=True for dnf
  lineinfile:
    path: /etc/dnf/dnf.conf
    search_string: fastestmirror
    line: fastestmirror=True

- name: Ensure base packages are installed
  dnf:
    name:
      - '*' # update packages
      - dnf-utils # provides 'needs-restarting' for kured
    state: present
