---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-videos
  namespace: {? {.Release.Namespace: ''} : ''}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: pv-nfs-videos
  storageClassName: nfs-csi-videos
