---
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Ktchn8s
site_url: http://localhost:8000
copyright: Copyright &copy; 2025 - present, serpro69

repo_url: https://github.com/serpro69/Ktchn8s

plugins:
  - search
  - panzoom:
      always_show_hint: true

theme:
  favicon: assets/images/favicon_io_logo_6/favicon.ico
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: nord:light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: nord:dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.share
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
  icon:
    logo: material/kubernetes

extra_css:
  - assets/stylesheets/image.css
  - assets/stylesheets/extra.css
  - assets/stylesheets/nord.css

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.superfences:
      custom_fences:
        # mermaid support
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path:
        # https://www.mkdocs.org/user-guide/configuration/#paths-relative-to-the-current-file-or-site
        - !relative $config_dir
        - !relative $docs_dir
      check_paths: true
  - pymdownx.tasklist:
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - "~/": index.md
  - "☰ Conceps":
      - concepts/development-shell.md
      - concepts/pxe-boot.md
  - "☲ Installation":
      - "☱ Production":
          - installation/production/network.md
          - installation/production/metal.md
  - "☵ Referece":
      - "☴ Architecture":
          - reference/architecture/overview.md
          - reference/architecture/network.md
          - reference/architecture/decision-records.md
      - reference/license.md
      - reference/changelog.md
      - reference/roadmap.md
      - reference/todo.md
  - "☷ Guides":
      - guides/how_to_configure_minicom.md
      - guides/how_to_add_or_remove_nodes.md
