# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.2/charts/other/app-template/values.schema.json
---
app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/jellyfin/jellyfin
            tag: 10.10.7
        transmission:
          image:
            repository: lscr.io/linuxserver/transmission
            tag: 4.0.6
        prowlarr:
          image:
            repository: lscr.io/linuxserver/prowlarr
            tag: 1.37.0
        radarr:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: 5.26.2
        sonarr:
          image:
            repository: lscr.io/linuxserver/sonarr
            tag: 4.0.15
        jellyseerr:
          image:
            repository: docker.io/fallenbagel/jellyseerr
            tag: 2.7.0
  service:
    main:
      ports:
        http:
          port: 8096
          protocol: HTTP
        transmission:
          port: 9091
          protocol: HTTP
        prowlarr:
          port: 9696
          protocol: HTTP
        radarr:
          port: 7878
          protocol: HTTP
        sonarr:
          port: 8989
          protocol: HTTP
        jellyseerr:
          port: 5055
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &jellyfinHost jellyfin.0xbad.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
        - host: &transmissionHost transmission.0xbad.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: transmission
        - host: &prowlarrHost prowlarr.0xbad.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: prowlarr
        - host: &radarrHost radarr.0xbad.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: radarr
        - host: &sonarrHost sonarr.0xbad.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: sonarr
        - host: &jellyseerrHost jellyseerr.0xbad.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: jellyseerr
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *jellyfinHost
            - *transmissionHost
            - *prowlarrHost
            - *radarrHost
            - *sonarrHost
            - *jellyseerrHost
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 50Gi
      advancedMounts:
        main:
          main:
            - path: /config
              subPath: jellyfin/config
            - path: /media/movies
              subPath: movies
            - path: /media/shows
              subPath: shows
          transmission:
            - path: /config
              subPath: transmission/config
            - path: /downloads
              subPath: transmission/downloads
          prowlarr:
            - path: /config
              subPath: prowlarr/config
          radarr:
            - path: /config
              subPath: radarr/config
            - path: /downloads/complete
              subPath: transmission/downloads/complete
            - path: /movies
              subPath: movies
          sonarr:
            - path: /config
              subPath: sonarr/config
            - path: /downloads/complete
              subPath: transmission/downloads/complete
            - path: /shows
              subPath: shows
          jellyseerr:
            - path: /app/config
              subPath: jellyseerr/config
    dri-devices:
      enabled: true
      type: hostPath
      hostPath: /dev/dri
      advancedMounts:
        main:
          main:
            - path: /dev/dri
              readOnly: false
    anothervideos:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: pvc-nfs-videos
      advancedMounts:
        main:
          main:
            - path: /media/Videos
              readOnly: false
