---
users:
  - name: renovate
    fullName: Renovate
    email: bot@renovateapp.com
    tokenSecretRef: renovate-secret
organizations:
  - name: ops
    description: Operations
    teams:
      - name: Owners
        members:
          - renovate
repositories:
  - name: homelab
    owner: ops
    private: false
    migrate:
      source: https://github.com/serpro69/Ktchn8s
      mirror: false
