# vim: set ft=yaml.ansible:
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
---
- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - role: prerequisites
  tags:
    - k3s
    - prerequisites

- name: Install K3s Control Plane
  hosts: control_plane
  # gather_facts: true # Already gathered if prerequisites ran on 'metal'
  roles:
    - role: k3s
  tags:
    - k3s
    - control

- name: Install K3s Worker Nodes
  hosts: nodes
  # gather_facts: true
  roles:
    - role: k3s
  tags:
    - k3s
    - nodes

- name: Install Kubernetes addons
  hosts: localhost # Cilium is installed via kubectl/helm from the management node
  roles:
    - role: cilium
  tags:
    - cilium
