# vim: set ft=yaml.ansible:
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
---
- name: Create Kubernetes cluster
  hosts: metal # This will run prerequisites on ALL metal hosts
  roles:
    - role: prerequisites # Installs necessary packages like curl, conntrack, etc.
      # - role: k3s # Moved k3s role to specific groups

- name: Install K3s Control Plane
  hosts: control_plane # Matches your inventory group
  # gather_facts: yes # Already gathered if prerequisites ran on 'metal'
  roles:
    - role: k3s # This role will now apply to control_plane hosts
      # The k3s role tasks need to differentiate between first control_plane and others

- name: Install K3s Worker Nodes
  hosts: nodes # Matches your inventory group for workers
  # gather_facts: yes
  roles:
    - role: k3s # This role will apply to worker nodes, configured as agents

- name: Install Kubernetes addons (Cilium)
  hosts: localhost # Cilium is installed via kubectl/helm from the control node
  roles:
    - role: cilium
