---
roles: []
collections:
  - name: community.general
    version: ">=10.7.1"
    source: https://galaxy.ansible.com
  - name: kubernetes.core
    version: ">=5.3.0"
    source: https://galaxy.ansible.com
