# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.2/charts/other/app-template/values.schema.json
---
app-template:
  controllers:
    cloudflared:
      containers:
        app:
          image:
            repository: docker.io/cloudflare/cloudflared
            tag: 2025.7.0
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
  configMaps:
    config:
      enabled: true
      suffix: config
      data:
        config.yaml: |
          tunnel: homelab
          credentials-file: /etc/cloudflared/credentials.json
          metrics: 0.0.0.0:2000
          no-autoupdate: true
          ingress:
            - hostname: '*.0xbad.cloud'
              service: https://ingress-nginx-controller.ingress-nginx
              originRequest:
                noTLSVerify: true
            - service: http_status:404
  persistence:
    config:
      enabled: true
      type: configMap
      name: cloudflared-config
      globalMounts:
        - path: /etc/cloudflared/config.yaml
          subPath: config.yaml
    credentials:
      enabled: true
      type: secret
      # Created by ../../external/cloudflared
      name: cloudflared-credentials
      globalMounts:
        - path: /etc/cloudflared/credentials.json
          subPath: credentials.json
