---
renovate:
  cronjob:
    schedule: '0 9 * * *' # daily at 0900
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "http://gitea-http.gitea:3000/api/v1",
        "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
        "autodiscover": true,
        "automerge": false
      }
  existingSecret: renovate-secret
