---
roles: []
collections:
  - name: community.general
    version: ">=10.6.0"
    source: https://galaxy.ansible.com
  - name: kubernetes.core
    version: ">=5.2.0"
    source: https://galaxy.ansible.com
