---
- name: Check that we're on the correct network
  assert:
    that: hostvars['localhost']['ansible_all_ipv4_addresses'] | ansible.utils.ipaddr(homelab_cidr)
    fail_msg: |
      No ipv4 addresses found within {{ homelab_cidr }}
      Available ipv4 addresses on {{ ansible_hostname }} are:
        {{ hostvars['localhost']['ansible_all_ipv4_addresses'] }}

- name: Ensure PXE server prerequisites
  include_tasks:
    file: before.yml
  when: pxe_state == "present"

- name: Clean up old PXE server containers
  community.docker.docker_compose_v2:
    project_src: "{{ role_path }}/files"
    state: absent
    build: always
  when: pxe_state != "absent"

- name: Start the ephemeral PXE server
  community.docker.docker_compose_v2:
    project_src: "{{ role_path }}/files"
    state: "{{ pxe_state }}"
    build: always
