---
woodpecker:
  agent:
    replicaCount: 2
    env:
      WOODPECKER_BACKEND_K8S_STORAGE_RWX: false
      # Agents will spawn pods to run workflow steps using the
      # Kubernetes backend instead of running them directly on
      # the agent pod, so we can run many workflows per agent.
      WOODPECKER_MAX_WORKFLOWS: 10
    mapAgentSecret: false
    extraSecretNamesForEnvFrom:
      - woodpecker-secret
  server:
    env:
      WOODPECKER_HOST: https://ci.0xbad.cloud
      WOODPECKER_WEBHOOK_HOST: http://woodpecker-server.woodpecker
      WOODPECKER_GITEA: true
      WOODPECKER_GITEA_URL: https://git.0xbad.cloud
      WOODPECKER_OPEN: true
      WOODPECKER_ADMIN: gitea_admin
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ingressClassName: nginx
      hosts:
        - host: &host ci.0xbad.cloud
          paths:
            - path: /
      tls:
        - secretName: woodpecker-tls-certificate
          hosts:
            - *host
    createAgentSecret: false
    extraSecretNamesForEnvFrom:
      - woodpecker-secret
    prometheus:
      podmonitor:
        enabled: true
      rules:
        enabled: true
    grafana:
      dashboards:
        enabled: true
        labels:
          grafana_dashboard: "1"
    metrics:
      enabled: true
