---
ansible_ssh_private_key_file: ~/.ssh/homelab_id_ed25519
ssh_public_key: "{{ lookup('file', '~/.ssh/homelab_id_ed25519.pub') }}"
dns_server: "8.8.8.8"

# TODO: exclude from DHCP
control_plane_endpoint: 10.10.10.100

load_balancer_ip_pool:
  # 10.10.10.40 - 10.10.10.69
  - 10.10.10.40/29
  - 10.10.10.48/28
  - 10.10.10.64/30
  - 10.10.10.68/31

homelab_net_cidr: 10.10.10.1/24
